### ISSUE TITLE
Implement DashStyle for Pen

### ISSUE THREAD

**Issue by kekekeks** [Perspex/Perspex#125]
Needed for HtmlRenderer

**Comment by grokys** [comment]
`Shape` has a `StrokeDashArray` property which does the same. However, `Shape`'s API is copied from WPF where the stroke is implemented as separate properties directly on `Shape` rather than using a `Pen`. Should we change to using a `Pen` for `Shape.Stroke`? Any idea why WPF uses separate properies? Possibly to make XAML parsing easier?

**Comment by ncarrillo** [comment]
#131 implements DashStyle and related properties on Pen. 
re: Shape, no idea. I say we unify it under Pen until its not a good idea anymore.
