### ISSUE TITLE
Avoid Pack URIs

### ISSUE THREAD

**Issue by ReedCopsey** [Perspex/Perspex#282]
It'd be nice if you could just about _anything_ other than Pack URIs to define locations.

Something like `Source="{Location Themes/Skins/Blue.xaml, Assembly=SkinBox.Controls}"` and  `Source="{Location External=http://Foo.bar/baz.xaml}"` (with Internal implied in the first, and Assembly optional if in the same assembly) would be much more understandable than trying to do:

`Source="pack://application:,,,/SkinBox.Controls;component/Themes/Skins/Blue.xaml"`

**Comment by grokys** [comment]
I like this idea! I will begin working on something along these lines shortly and post the proposed syntax here.

**Comment by kekekeks** [comment]
Uniform format: `res:///[assembly]/path`
For locating stuff in current assembly by absolute local path:
- Relative uri with leading slash: `/My.Full.Path.To.Resource`
- Absolute uri: `res:////My.Full.Path.To.Resource` (won't be used in XAML, because it's equivalent to the previous one which is much shorter and readable)


Locating stuff in other assembly:
 -Absolute uri: `res:///Assembly/My.Full.Path.To.Resource`

We are using `res:///` with empty host, because host component is [case-insensetive](https://tools.ietf.org/html/rfc3986#section-3.2.2) while assembly names aren't, on *nix systems that might cause problems.

`res:////` with four slashes is valid, because it has empty `assembly` part which makes asset loader to default to current assembly.

For now we won't support relative uris because EmbeddedResource build action erases information about actual directory structure.

**Comment by grokys** [comment]
Confirmed that on mono, case-sensitivity of `Assembly.Load` would cause problems.

**Comment by SuperJMN** [comment]
*If it were possible for OmniXAML to pass the URL that the XAML file was being loaded from to the  TypeConverters  then we could probably also handle relative paths in this manner.*

I would need to understand this! OmniXAML is "location-agnostic", so it doesn't know anything about Uris or paths. It only understands instructions.

**Comment by kekekeks** [comment]
@SuperJMN  we needsome context argument to be passed to `XamlLoader.Load` so OmniXAML can pass it to type converters. That will allow caller to pass arbitrary data to converters, including the location of the file.
